### ISSUE TITLE
[SailfishOS lockscreen] change color when LPM active

### ISSUE THREAD

**Issue by CODeRUS** [Meecast/meecast#15]
Please use ```textColor``` property as color for texts and widget border. It will allow widget to change color in LPM mode.
![screenshot-01-02-15-22-49-29](https://cloud.githubusercontent.com/assets/720601/5993049/a9133cf8-aa64-11e4-9de5-c590a5ecd06c.png)

**Comment by vasvlad** [comment]
Fixed in the version 0.2 of harbour-meecast-lockscreen package

**Comment by CODeRUS** [comment]
Thanks!

**Comment by CODeRUS** [comment]
Sorry, but city and update date is not colored :)
![screenshot-02-02-15-13-07-34](https://cloud.githubusercontent.com/assets/720601/5997399/937d0126-aadc-11e4-8961-4cedddfcee7f.png)

**Comment by CODeRUS** [comment]
And can you please disable lower transparent layer when lipstickSettings.lowPowerMode is true?

**Comment by vasvlad** [comment]
Thanks for bug reports.
It has been fixed in the version 0.4 of Lockscreen package
