### ISSUE TITLE
cast update

### ISSUE THREAD

**Issue by ryzhikgagarin** [Meecast/meecast#16]
Здравствуйте! 
Проявляются два бага.

1) После обновления прогноза вручную, через некоторое время вся информация пропадает. Затем, длительное время не обновляется, ни автоматически, ни вручную. Особенно, если настроен сервер gismeteo. Между тем, с браузера сайт доступен. 

2) Информацию в разделе "ночь" показывает только на сегодняшние сутки. На остальную неделю на экране отабражены какието теги: 
unedined
Project-Id-Version:
Report-Msgid-Bugs-
POT-Creation-Date:
и т.д.

Meecast 0.9.13
Nokia N9 MeeGo Harmattan.

**Comment by vasvlad** [comment]
Скоро выйдет версия 1.0. Проверьте будет ли там эта проблемаю

**Comment by jazzmale** [comment]
Версия 1.0.3

1) gismeteo и foreca все так же недоступны. 

2) Все так же, в разделе "ночь" отображены теги.

**Comment by vasvlad** [comment]
Существует ли сейчас эта проблема?

**Comment by jazzmale** [comment]
Да, эта проблема все еще есть..!
1) Некоторые каналы не обновляются. 
2) Все так же, в разделе "ночь" на завтра и далее отображены теги.

**Comment by vasvlad** [comment]
Очень странно

2015-08-16 15:20 GMT+03:00 jazzmale <notifications@github.com>:
