### ISSUE TITLE
49710 days ago...older as my N9

### ISSUE THREAD

**Issue by DeadHorseRiding** [Meecast/meecast#17]
Only temporary/cosmetic this day

![20150401111953](https://cloud.githubusercontent.com/assets/10514536/6941302/039e1b3c-d87f-11e4-83be-2f8700472993.png)

![20150401111921](https://cloud.githubusercontent.com/assets/10514536/6941303/0925472e-d87f-11e4-9b12-04fe3835e18c.png)

and normal again same hours later

![20150401135858](https://cloud.githubusercontent.com/assets/10514536/6941308/0eee5bd2-d87f-11e4-8e91-456dff86aad8.png)

**Comment by vasvlad** [comment]
What did you mean?
I don't see pictures in this bug report. :(

**Comment by vasvlad** [comment]
Ok. Now. I see it. But I don't how I can catch this situation :(

**Comment by DeadHorseRiding** [comment]
Vlad, you are to fast.

Not usual/urgent problem.

I am working (for little money) this time by phone. 
May interrupt next time by work for some hours. 

First 2 Pictures saved in train to work this morning.

**Comment by DeadHorseRiding** [comment]
> But I don't how I can catch this situation :(
Yes, not reproducable...заархивировать?

**Comment by vasvlad** [comment]
no.

**Comment by Olf0** [comment]
I observed the same issues and documented it as **Bug 3** at issue #35.

The small differences are only:
* The number of days displayed: 18417 vs. 49710
* The weather data provider for the station: Foreca.com vs. Weather.com
* The MeeCast version used: v1.1.25-16 vs. likely v0.9.15-1
