### ISSUE TITLE
Meecast ignores update intetval on launch

### ISSUE THREAD

**Issue by Self-Perfection** [Meecast/meecast#19]
I prefer to avoid using meecast daemon to preserve ram, but occasionally run meecast to check forecast.

I have  set update interval to 2 hours and expect meecast to do reasonable effort to ensure, that I don't ever see forecast which is older than 2 hours.

In my opinion meecast should check on launch age of downloaded forecast and start update automatically if it is older than configured update interval.

**Comment by vasvlad** [comment]
Meecast refreshes forecast after expire time of updating  (try to add new station and switch to it). But meecast (as almost all sailfish's standalone application) doesn’t work correctly in background mode (application go to sleep mode).

**Comment by Self-Perfection** [comment]
Мне кажется, я был неправильно понят, давайте ещё раз на более привычным нам языке :)

Рассмотрим случай, когда meecastd не используется, т.е. обновления прогноза происходят только из meecast. Предположим у пользователя meecast не был запущен в течение последней недели, и вот сейчас пользователь его запускает, чтобы посмотреть прогноз погоды на завтра. И даже какой-то прогноз видит, вот только это прогноз недельной давности. И пользователь должен вспомнить/догадаться, что нужно вручную запустить обновление.

В настройках есть "интервал обновления", который можно выставить <=4 часа. Почему при запуске не происходит проверка на то, что имеющий скачанный прогноз погоды имеет давность более чем "интервал обновления" и не происходит автоматическое обновление прогноза сразу после запуска?

**Comment by vasvlad** [comment]
Такая проверка происходит и прогноз обновляется, если в это время есть соединение с Интернетом.

**Comment by Self-Perfection** [comment]
Попробовал разобраться/поэкспериментировать. У меня это проверка не то что бы совсем не работает, но очень глючит.

В 18:08 запустил обновление вручную и завершил meecast:
```
$ ls -l ~/.config/harbour-meecast/gismeteo.ru_4368*
-rw-r--r-- 1 nemo nemo  25046 2015-08-16 18:08 /home/nemo/.config/harbour-meecast/gismeteo.ru_4368
-rw-r--r-- 1 nemo nemo  72783 2015-08-16 18:08 /home/nemo/.config/harbour-meecast/gismeteo.ru_4368.detail.orig
-rw-r--r-- 1 nemo nemo 122479 2015-08-16 18:08 /home/nemo/.config/harbour-meecast/gismeteo.ru_4368.orig
```
Интервал обновления выставлен в 15 минут. В 18:37 ещё раз запустил и завершил:
```
$ ls -l ~/.config/harbour-meecast/gismeteo.ru_4368*
-rw-r--r-- 1 nemo nemo  25046 2015-08-16 18:08 /home/nemo/.config/harbour-meecast/gismeteo.ru_4368
-rw-r--r-- 1 nemo nemo      0 2015-08-16 18:37 /home/nemo/.config/harbour-meecast/gismeteo.ru_4368.detail.orig
-rw-r--r-- 1 nemo nemo 122400 2015-08-16 18:37 /home/nemo/.config/harbour-meecast/gismeteo.ru_4368.orig
```
А куда делся detail.orig? Да и собственно прогноз, похоже, не обновился...

Затем, не ждя, в эту же минуту снова запустил:
```
$ ls -l --full-time ~/.config/harbour-meecast/gismeteo.ru_4368*
-rw-r--r-- 1 nemo nemo      0 2015-08-16 18:37:58.587810242 +0300 /home/nemo/.config/harbour-meecast/gismeteo.ru_4368
-rw-r--r-- 1 nemo nemo  72627 2015-08-16 18:37:58.517735467 +0300 /home/nemo/.config/harbour-meecast/gismeteo.ru_4368.detail.orig
-rw-r--r-- 1 nemo nemo 122400 2015-08-16 18:37:58.447660692 +0300 /home/nemo/.config/harbour-meecast/gismeteo.ru_4368.orig
```
И meecast показывал текст "похоже, нет данных для этого положения, попробуйте обновить".

Итого я заключаю, что описанный мной выше сценарий с запуском через неделю и просмотром устаревшего прогноза с такими багами вполне возможен, раз фактическое обновление происходит с третьего раза. Собственно что-то в таком духе я и наблюдал, что и привело меня к созданию issue.

**Comment by vasvlad** [comment]
Ok. Спасибо за тесты

2015-08-16 18:52 GMT+03:00 Alexander <notifications@github.com>:
