### ISSUE TITLE
"(null)" instead of status message

### ISSUE THREAD

**Issue by Self-Perfection** [Meecast/meecast#20]
I often get (null) as description of current weather condition
![screenshot-21-07-15-23-09-28](https://cloud.githubusercontent.com/assets/3757038/8823311/89f991fa-3074-11e5-89a7-53e7879b4df3.png)

I use harbour-meecast-1.1.2-32

**Comment by vasvlad** [comment]
I will add some translations of weather states for gismeteo.ru in the next release(1.1.3).
