### ISSUE TITLE
Screen and Font size need to adjust to fit JollaC or Aquafish

### ISSUE THREAD

**Issue by TMavica** [Meecast/meecast#26]
Now all thing is small

**Comment by maslovalex** [comment]
Same thing on tablet. Everything is too small.

**Comment by w32blaster** [comment]
I have installed SailfishOS to the Nexus5. The same issues. Screeshots are attached.

![screenshot-16-07-31-21-55-10](https://cloud.githubusercontent.com/assets/6038179/17300142/09c25aea-5809-11e6-9e9f-dc10b1f5db60.png)

![screenshot-16-07-31-23-39-16](https://cloud.githubusercontent.com/assets/6038179/17300152/1201d636-5809-11e6-97b5-c3c74551c124.png)

![screenshot-16-07-31-21-51-10](https://cloud.githubusercontent.com/assets/6038179/17300164/1db1e264-5809-11e6-8bf0-02cd2121cd7a.png)

**Comment by vasvlad** [comment]
It will be fixed soon

**Comment by vasvlad** [comment]
Fixed in version 1.1.13
