### ISSUE TITLE
gismeteo.ua as a data source

### ISSUE THREAD

**Issue by efscher** [Meecast/meecast#29]
Would it be hard to add gismeteo.ua as a data source?

**Comment by vasvlad** [comment]
It seems that the data from gismeteo.ua and gismeteo.ru are not difference.

**Comment by efscher** [comment]
OK, so a whole lot of cities are visible on the websites, but aren't in the data you use for meecast...  Here's an example:  

https://www.gismeteo.ru/weather-kosiv-12063/

**Comment by vasvlad** [comment]
I can add this station to gismeteo source. What other stations you would like to see in Meecast?

**Comment by efscher** [comment]
I guess asking for all of them is way too much, so these 3 would do for me:

https://www.gismeteo.ru/weather-sniatyn-12067/
https://www.gismeteo.ru/weather-yavoriv-83389/
https://www.gismeteo.ru/weather-turya-pasika-13409/

Thanks!

**Comment by vasvlad** [comment]
Done. It available in the version 1.1.18 on openrepos.net
