### ISSUE TITLE
No data downloaded for dates after the 31st of December

### ISSUE THREAD

**Issue by Olf0** [Meecast/meecast#32]
The usual bug occurs this year (2018 -> 2019) as every turn of the year (filing it properly this time, here):
No data downloaded for dates after the 31st of December (until it is the 1st of January, at least in previous years).
Originally [reported by @naalaa](https://openrepos.net/comment/23092#comment-23092).

Tested (this time) with Meecast 1.1.20 under SailfishOS 2.2.1.18, using Weather.com as data provider.
This also occurred the years before, with the then recent releases of Meecast and SailfishOS, also using Weather.com's data.

P.S.: Issue #31 is probably related to this issue.

**Comment by vasvlad** [comment]
Fixed

**Comment by Olf0** [comment]
Retested with with MeeCast 1.1.23-8 and 1.1.24-1 (using weather.com as data provider) on SailfishOS 2.2.1 and 3.2.1: Yes, this was already fixed in v1.1.23-8, hence v1.1.24-1 is fine, too.
Thanks!
