### ISSUE TITLE
Reported issues with 64-bit devices

### ISSUE THREAD

**Issue by Olf0** [Meecast/meecast#36]
For now this is just a placeholder issue.

There are issues with 64-bit devices (Xperia 10 II and PinePhone) [reported at OpenRepos](https://openrepos.net/comment/38065#comment-38065).  The report comes with a little analysis and a clumsy workaround (a lot of symlinks), which needs to be improved (at least by using relative links).

I will re-analyse this more thoroughly, when I get around to flash my Xperia 10 II with SailfishOS.
Hopefully I manage to write something more concise or even pose a PR, then.

Until then: Don't worry @vasvlad, I know you lack time, so I will not bother you, until I have a proper analysis and something real to discuss or implement.

**Comment by Olf0** [comment]
### Update
@teleshoes has provided 64-bit builds at OpenRepos:
* [Meecast Daemon aarch64](https://openrepos.net/content/teleshoes/meecast-daemon-aarch64)
* [Meecast Event View aarch64](https://openrepos.net/content/teleshoes/meecast-event-view-aarch64)
* [meecast-lockscreen aarch64](https://openrepos.net/content/teleshoes/meecast-lockscreen-aarch64)

I have not tested yet, if these are working well.  I plan to do that later this year.

**Comment by vasvlad** [comment]
64-bit versions are available on OpenRepos after the version 1.1.33 of MeeCast
