### ISSUE TITLE
Events views not working in new version of SailfishOS

### ISSUE THREAD

**Issue by juanro49** [Meecast/meecast#37]
Hi! in the latest versions of SailfishOS the event view does not work. from what I saw, it is because the binaries contain inside the binaries the nemo home instead of the new default user called "defaultuser".

More in https://forum.sailfishos.org/t/4-4-0-58-meecast-bug-event-view-not-working/11426

**Comment by Olf0** [comment]
Workaround:
`cd /home; devel-su ln -s defaultuser nemo`

**Comment by vasvlad** [comment]
Please check this problem in the new version 1.1.34 of MeeCast.

**Comment by poetaster** [comment]
I just tested 1.1.35 and the eventview seems fine.

**Comment by juanro49** [comment]
Yes, latest version work fine!
