### ISSUE TITLE
The `.desktop` file for SailfishOS lacks a "Sailjail" section

### ISSUE THREAD

**Issue by Olf0** [Meecast/meecast#38]
For a trivial Sailjail section, simply opting out of Sailjail, see [the one of Storeman](https://github.com/storeman-developers/harbour-storeman/blob/73e1490feb24c7e6c952249de76ef7ba1feaa504/harbour-storeman.desktop#L9-L10):
```
[X-Sailjail]
Sandboxing=Disabled
```

**Comment by vasvlad** [comment]
Fixed in the version 1.3.33

**Comment by Olf0** [comment]
… by commit https://github.com/Meecast/meecast/commit/8889de1ec0997fa89bbb93055d5937084513a403 via PR #40.
