### ISSUE TITLE
Bom.gov.au as weather source shows the previous day.

### ISSUE THREAD

**Issue by poetaster** [Meecast/meecast#41]
Reported on the forum:

https://forum.sailfishos.org/t/meecast-forecast-info-and-dates-wrong-x10-iii/16760

In addition, the dates and forecast info are out of allignment by a few days.

**Comment by vasvlad** [comment]
Fixed in the version 1.1.35

**Comment by poetaster** [comment]
Thanks! I just wanted to let you know I had fiddled around with the build script on my fork which now automatically produces the release:
https://github.com/poetaster/meecast/releases

The build.yaml I'm using is not finished (builds on push to branch AND tag), but I wanted to ask if I should pursue this?

**Comment by vasvlad** [comment]
Hi.
Good work!
I'm waiting the merge request from you.

**Comment by poetaster** [comment]
> Hi. Good work! I'm waiting for a merge request from you.

Ok. How I usually use these is to have a reserved token for release and so have two types of tags. I ONLY use tag pushes (in my case with a 'v' prefix) to cause build / release. 

The question is are you ok with using a prefix? One could also just  a pattern of tag (1.3.* or the like).  

I guess it could also be on any push to the 'sailfishos' branch if you prefer.

I keep the types of tags separate to also allow me to tag slightly different builds for CHUM or openrepos in contrast to harbour.

**Comment by vasvlad** [comment]
I think that using 'V'  prefix in tag is a good idea
