### ISSUE TITLE
obs/chum integration

### ISSUE THREAD

**Issue by poetaster** [Meecast/meecast#43]
So, I've just gotten this building on obs:

https://build.sailfishos.org/package/show/home:poetaster/meecast

It's on my sailfishos branch, using tag 1.1.36 currently. I'm going to add meta data for chum (display in the gui) and then I'll do a PR if that sounds right. 

The meta, for the moment looks like:
```
%if "%{?vendor}" == "chum"
PackageName: Meecast
Type: desktop-application
Categories:
 - Science
 - News
DeveloperName: Uladzislau Vasilyeu and Omweather team
Custom:
 - Repo: https://github.com/meecast/meecast
Icon: https://github.com/Meecast/meecast/blob/master/meecast/core/data/desktop/Icon/128/meecast.png?raw=true
%endif
```

**Comment by poetaster** [comment]
Just tested the 1.1.36 build on chum testing. Works fine. Also tested the yr.no provider and it seems to work, too. I'll make a PR as soon as I've squashed.

**Comment by vasvlad** [comment]
ok

**Comment by poetaster** [comment]
rinigus just noted an error (well, I missed one). I'll add that missing one now.
BuildRequires: qml(Sailfish.Silica) is the missing one.
