### ISSUE TITLE
Change provider with gps fetched location

### ISSUE THREAD

**Issue by legacychimera247** [Meecast/meecast#45]
Hello there, using meecast with latest 4.5.0.24 release and an xa2, noticed the gps fetched location does almost not work

i mean, i thought it was not working but then i realized it's just the wheater channel not having my city, ok it might be as it's a small city (almost) but it's fetching a position really far away (like also 100 km away)

Now i'm actually in a really big town but still gps location is literally wrong

it would be nice if we could change the provider used in the gps fetching, supposedly for example foreca has more locations

**Comment by vasvlad** [comment]
hi.
Gps fetching in MeeCast seem likes work incorrectly. But currently I have no any free time to fix it. :(. 
Currently default source of gps station is weather.com. I can try to add your city to weather.com database for quick fix your problem.

**Comment by legacychimera247** [comment]
Don't worry, it was just for convenience, but foreca has my city and it's the most reliable

what about adding it to yr.no?cause yr.no on computer has my city but not meecast

**Comment by vasvlad** [comment]
No problem. I can add station to yr.no database.

**Comment by legacychimera247** [comment]
Yeah thank you, should i tell you my postal code or my city?

**Comment by vasvlad** [comment]
I need know your Country / City

**Comment by legacychimera247** [comment]
Ok, my country is italy then, and my city is giulianova :)

**Comment by vasvlad** [comment]
I've added station Giulianova in Italy to weather.com and yr.no sources. And I've  fixed  wrong gps-coordinates Teramo(Italy) station(source yrno). You can try it as gps station (weather.com) and simple station (yr.no) in the version 1.1.38 of MeeCast.

**Comment by legacychimera247** [comment]
Thank you :)
