### ISSUE TITLE
Unbundle in-tree libraries

### ISSUE THREAD

**Issue by Thaodan** [Meecast/meecast#47]
I noticed that meecast features some in tree libraries such as dconf, libxml2, sqlite etc.
Would it make sense to get rid of those?

**Comment by vasvlad** [comment]
MeeCast needs those libraries

**Comment by Thaodan** [comment]
Did you the text above? It's not about removing them from the program but about not bundling them.

**Comment by Thaodan** [comment]
If you don't get what I'm saying please just ask.
