### ISSUE TITLE
Meecast Event View does not display anything on SailfishOS 4.6.0

### ISSUE THREAD

**Issue by Olf0** [Meecast/meecast#48]
AFAIU Meecast Event View (`harbour-meecast-event`) is also affected by [this change in SailfishOS 4.6.0](https://forum.sailfishos.org/t/sfos-4-6-foreca-how-to-enable-the-weather-infos-is-in-the-the-events-view/18678/5?u=olf), which is in Jolla's tradition to introduce changes which break for third-party apps unnecessarily.

Consequently the `harbour-meecast-event` RPM file would need to `Require: lipstick-jolla-home-qt5-weather-widget-settings`, but only on SailfishOS ≥ 4.6.0.0.
E.g. by adding this to the body of the RPM spec file:
```
# Detect missing Lipstick Weather Widget on SFOS > 4.6.0.0
%if %{defined sailfishos_version} && 0%{?sailfishos_version} > 46000
%define add_weather_widget 1
%endif

# Require Lipstick Weather Widget on SFOS > 4.6.0.0
%if 0%{?add_weather_widget}
Require: lipstick-jolla-home-qt5-weather-widget-settings 
%endif
```
and in the `%post` section of the RPM spec file:
```
# Activate Lipstick Weather Widget on SFOS > 4.6.0.0
%if 0%{?add_weather_widget}
dconf write /desktop/lipstick-jolla-home/force_weather_loading true
exit 0
%endif
```

HTH

P.S.: I understood that Meecast Event View is affected only by reading e.g. [post \#6](https://forum.sailfishos.org/t/sfos-4-6-foreca-how-to-enable-the-weather-infos-is-in-the-the-events-view/18678/6?u=olf) and [post \#13](https://forum.sailfishos.org/t/sfos-4-6-foreca-how-to-enable-the-weather-infos-is-in-the-the-events-view/18678/13?u=olf) in the FSO-thread "[SFOS 4.6 (Foreca / Meecast): How to (re-)enable the weather infos in Events View](https://forum.sailfishos.org/t/18678?u=olf)" and some posts in the FSO-thread "[[Release notes] Sauna 4.6.0.11](https://forum.sailfishos.org/t/release-notes-sauna-4-6-0-11/17815?u=olf)".

**Comment by vasvlad** [comment]
Done.
https://openrepos.net/content/vasvlad/meecast-event-view
Thanks so much  Olf0.

**Comment by Olf0** [comment]
> https://openrepos.net/content/vasvlad/meecast-event-view
> Thanks so much Olf0.

You are welcome.  BTW, just realised that I am using your triplet comprising `Meecast`, `Meecast daemon` and  `Meecast Events View` for more than 10 years. :smiley:

I hope PR #49 is working fine: I have not tested it, as I will never use EA ("Early Access") releases of SailfishOS and am quite reluctant to upgrade SailfishOS on my devices.

But I assume users will tell: here, at OpenRepos or at FSO.

**Comment by Olf0** [comment]
There still seems to be a flaw under SailfishOS 4.6.0, im am awaiting feedback, see [messages 16 and 17 in this thread at FSO](https://forum.sailfishos.org/t/sfos-4-6-foreca-meecast-how-to-re-enable-the-weather-infos-in-events-view/18678/16?u=olf).

**Comment by vasvlad** [comment]
I can't try it. :( I've bought Sony Experia 10 V for experiments. But  I can't have access EA ("Early Access") for this device.

**Comment by Olf0** [comment]
> I can't try it. :( I've bought Sony Xperia 10 V for experiments. But I can't have access EA ("Early Access") for this device.

Do not worry Vlad, I am trying to get this tested by people at FSO, see aforementioned thread.

I cannot try this, too, because I do not *want* to test EA releases, but I think others will.

**Comment by Olf0** [comment]
Oh, you only uploaded the `armv7hl` package of `harbour-meecast-event-1.1-2` [at OpenRepos](https://openrepos.net/content/vasvlad/meecast-event-view#main-content), but missed to upload the `i486` and `aarch64` packages.  That is an easy explanation why v1.1-**2** does not fix anything for most users, as they use 64-bit devices: Thus they install v1.1-**1**, because this is the latest version for `i486` and `aarch64`.

Hence please also upload the `i486` and `aarch64` packages of `harbour-meecast-event-1.1-2` [at OpenRepos](https://openrepos.net/content/vasvlad/meecast-event-view#main-content).

**Comment by Olf0** [comment]
Thank you; so [I asked for testing at FSO](https://forum.sailfishos.org/t/sfos-4-6-foreca-meecast-how-to-re-enable-the-weather-infos-in-events-view/18678/23#ps-1).

**Comment by Olf0** [comment]
> Packages for 4.6 [are here](https://build.sailfishos.org/project/show/home:vasvlad):

Thank you.  The [repository configuration](https://build.sailfishos.org/project/meta/home:vasvlad) looks a bit awkward to me, but it seems to have compiled fine.

Because I remember well, that the learning curve with OBS is a bit steep (additionally the Sailfish-OBS uses a outdated version), some suggestions:
1. Create a new project in [your OBS-home](https://build.sailfishos.org/project/show/home:vasvlad) called `meecast` .
2. IMO it is much easier to directly edit a OBS-project-configuration online than to use the various click options in OBS's web-frontend.  Hence open the project-configuration of [the project you just created](https://build.sailfishos.org/project/meta/home:vasvlad:meecast) and also open [the project-configuration of Storeman](https://build.sailfishos.org/project/meta/home:olf:harbour-storeman) in another browser tab to copy some lines.  Copy&paste at least this block:
   ```
     <repository name="4.6_i486">
       <path project="sailfishos:4.6" repository="latest_i486"/>
       <arch>i586</arch>
     </repository>
     <repository name="4.6_armv7hl">
       <path project="sailfishos:4.6" repository="latest_armv7hl"/>
       <arch>armv8el</arch>
     </repository>
     <repository name="4.6_aarch64">
       <path project="sailfishos:4.6" repository="latest_aarch64"/>
       <arch>aarch64</arch>
     </repository>
   ```
   You may also add me as a maintainer, then I can directly support you with these things (configuration etc.) at the Sailfish-OBS.
4. Create a package there, also called `meecast` .
5. Create a `_service` file locally on your computer with this content:
   ```
   <services>
     <service name="tar_git">
       <param name="url">https://github.com/Meecast/meecast.git</param>
       <param name="branch">sailfishos</param>
       <param name="revision"/>
       <param name="token"/>
       <param name="debian">N</param>
       <param name="dumb">N</param>
     </service>
   </services>
   ```
   Then upload this `_service` file to your package repository `meecast/meecast` at OBS.
   This `_service` configuration allows you to click on "Trigger services" in the package overview to build the current state of the branch `sailfishos` of Meecast.  For submitting this package to [the SailfishOS:Chum testing repository](https://build.sailfishos.org/project/show/sailfishos:chum:testing) you will have to temporarily set the `revision` to a valid git-tag, else it will not be accepted by rinigus / piggz.  After a package submission is accepted at SailfishOS:Chum testing once, this can be reverted for good, because then you can edit the package metadata for Meecast directly at SailfishOS:Chum testing.

**Comment by Olf0** [comment]
Oops, https://github.com/Meecast/meecast/pull/54/files#diff-ec2c6948f72f7af88a5d34b1612ef36a682c32f02015581a5542d592b2e1a7daL101-R101

My bad.  Please merge, rebuild and publish.  From what I gather at FSO this typo was the last hurdle, which prevented MeeCast Eventview from working (without additional, manual measures) after installation.

**Comment by vasvlad** [comment]
> Oops, https://github.com/Meecast/meecast/pull/54/files#diff-ec2c6948f72f7af88a5d34b1612ef36a682c32f02015581a5542d592b2e1a7daL101-R101
> 
> My bad. Please merge, rebuild and publish. From what I gather at FSO this typo was the last hurdle, which prevented MeeCast Eventview from working (without additional, manual measures) after installation.

I've just uploaded MeeCast Eventview  packages to openrepos.net

https://openrepos.net/content/vasvlad/meecast-event-view

**Comment by poetaster** [comment]
I had overlooked this, but it's building on chum now and should be available today.

**Comment by Olf0** [comment]
Thank you @poetaster, though I am [trying to guide @vasvlad](https://github.com/Meecast/meecast/issues/48#issuecomment-2170618142) to set up an own MeeCast package or subproject (the latter is preferable IMO; I edited the guide WRT this yesterday night) at the Sailfish-OBS in a way that he can submit it to SailfishOS:Chum:testing.  This would enable him to handle the whole release process for SailfishOS:Chum on his own, without triggering you (or me or anybody else).

You may consider to add him and/or me to the list of maintainers [in `SailfishOS:Chum:testing/meecast`'s meta configuration](https://build.sailfishos.org/package/meta/sailfishos:chum:testing/meecast) by adding these lines under the `<person userid="poetaster" role="maintainer"/>` one:
```
  <person userid="vasvlad" role="maintainer"/>
  <person userid="olf" role="maintainer"/>
```
This would eliminate the need for @vasvlad to submit MeeCast to SailfishOS:Chum:testing in order to be able to handle releases there on his own.
<sub>Unfortunately this way the preferred spelling `MeeCast` cannot be achieved, because package names at OBS cannot be directly altered retrospectively, only indirectly by submitting the package to a new name at the same project.  But this is a nitpick without any real relevance, IMO.</sub>

Still I would appreciate if @vasvlad would establish a proper subproject or/and package configuration in his OBS-"home" in order to test-compile MeeCast there: As some people use SailfishOS:Chum:testing, I believe one should not put outright broken builds there.  This is why I usually test-build apps in an own OBS-subrepository first (only for a few SailfishOS target releases), before I trigger a build at SailfishOS:Chum:testing.  Because the Sailfish-OBS tends to be slightly oversensitive WRT build configuration (spec file etc.), I do this in addition to CI builds at GitHub.

Thinking about it while writing the prior paragraph, I could actually create such a MeeCast OBS-subrepo in my OBS-"home" and add both of you as maintainers; may be nest weekend, when I have a little more time.

**Comment by Olf0** [comment]
My biggest, current concern WRT MeeCast is actually still a fully automatic (i.e. without additional, manual work) installation of MeeCast Eventview: I am [currently out of ideas what exactly goes wrong](https://forum.sailfishos.org/t/sfos-4-6-foreca-meecast-how-to-re-enable-the-weather-infos-in-events-view/18678/32?u=olf).  Hence any help is much appreciated.

**Comment by poetaster** [comment]
> My biggest, current concern WRT MeeCast is actually still a fully automatic installation (i.e. without additional, manual work) of MeeCast Eventview: I am [currently out of ideas what exactly goes wrong](https://forum.sailfishos.org/t/sfos-4-6-foreca-meecast-how-to-re-enable-the-weather-infos-in-events-view/18678/32?u=olf). Hence any help is much appreciated.

I've only had time to test the update in 4.5 which worked without issue.  As I understand it, the issue with the event view is the need to use dconf after the jolla event view deprecation (cough!)?

I'll add you both to the maintainers ... now.

**Comment by poetaster** [comment]
I've added you both to the obs testing repo, but do not have the authority on the chum repo proper. 

I'm not really sure about the automation myself, and do far too much  manual work even for having set up both webhooks (in subprojects) to respond to releases on github. I find that get's me 2/3s of the way there (using release semantics to drive github actions and a webhook on release for obs). Still, I end up building the packages for openrepos via the sdk to 'keep on top' of the behaviour of the sdk and see if I spot errors in the packaging on build. 

Hmmm. meta.

**Comment by Olf0** [comment]
> As I understand it, the issue with the event view is the need to use dconf after the jolla event view deprecation (cough!)?

Yes, and I think I am now at the point to address that properly with the current (as of today) code, but only at SailfishOS:Chum.  I know how to also achieve that at OpenRepos, but that is a lot more hassle to implement.  For the upcoming months the MeeCast Event package from OpenRepos will continue to require the two manual steps as described at FSO to work.

**Comment by Olf0** [comment]
Finally the `harbour-meecats-event` RPM compiled from the source tree [tagged `v1.1.39-3`](https://github.com/Meecast/meecast/releases) at [the Sailfish-OBS](https://build.sailfishos.org/project/show/home:olf:MeeCast) is installing fine and [running "out of the box" without any additional manual work](https://forum.sailfishos.org/t/sfos-4-6-foreca-meecast-how-to-re-enable-the-weather-infos-in-events-view/18678/48?u=olf) on SailfishOS 4.6.0. :tada: 
I submitted this to SailfishOS:Chum.

**Comment by Olf0** [comment]
I exchanged [SailfishOS:Chum:testing/meecast](https://build.sailfishos.org/package/show/sailfishos:chum:testing/meecast) with [SailfishOS:Chum:testing/MeeCast](https://build.sailfishos.org/package/show/sailfishos:chum:testing/MeeCast): All tree of us are still maintainers of this package.
Subsequently I requested the same exchange at SailfishOS:Chum proper: Adding [MeeCast](https://build.sailfishos.org/request/show/3442) and removing [meecast](https://build.sailfishos.org/request/show/3443).

@vasvlad, I also [suggest to remove OBS-package MeeCast at the Sailfish-OBS](https://build.sailfishos.org/request/show/3438), because its configuration has issues.

You and @poetaster have full maintainer access to [the package MeeCast in my sub-repository MeeCast](https://build.sailfishos.org/package/show/home:olf:MeeCast/MeeCast).  I now reconfigured it that hitting "Trigger services" compiles a git-checkout of the current state of the `sailfishos` branch here at GitHub, so it can be easily used for test-building: "Does it compile?" and one can try the generated packages.

**Comment by poetaster** [comment]
Thanks for the heads up. I haven't had time to test since test phone is  in a very odd state and I'm about to go on vacation ... so don't want to risk anything till I'm back in August :)

**Comment by Olf0** [comment]
That is fine.

Also, there is almost nothing to test: There is a fully working version for SailfishOS 4.6.0 at SailfishOS:Chum and I have a concept how to provide fully working versions, both for SailfishOS ≥&nbsp;4.6.0 and <&nbsp;4.6.0 at OpenRepos.
