### ISSUE TITLE
[Bug] Segmentation fault while trying to load fmi.fi stations

### ISSUE THREAD

**Issue by Ingvix** [Meecast/meecast#62]
Exact **OS NAME** and **OS VERSION**: 
Sailfish OS 4.5.0.24 (Struven ketju)

**HARDWARE**:
Sony Xperia 10 - Dual SIM

**MeeCast VERSION**: 
1.1.38

Installed **MeeCast PACKAGES**: 
harbour-meecast-1.1.39-2.armv7hl
harbour-meecast-daemon-1.10-2.armv7hl
harbour-meecast-event-1.1.40.2-1.1.1.jolla.armv7hl

**SOURCE of MeeCast PACKAGES**: 
Originally from OpenRepos via Storeman, but I'm pretty sure the current versions are from SailfishOS:Chum via SailfishOS:Chum GUI app.

**Weather data SOURCE(s)**: 
fmi.fi

**Weather LOCATION(s)**: 
fmi.fi:Finland:Southern Finland Province:Hämeenlinna
fmi.fi:Finland:Southern Finland Province:Hämeenkoski
fmi.fi:Finland:Southern Finland Province:Helsinki

#### BUG DESCRIPTION
None of the above stations are able to load the weather information and the app crashes if you press the button to fetch the weather.

#### STEPS TO REPRODUCE
Enable any of the above mentioned locations and press the button to fetch weather information.

#### ADDITIONAL INFORMATION

It's been like this a good while, but I was too lazy to create an issue about it, but I'd really prefer to have fmi.fi stations working again as they provide more information than foreca. I don't know if their API has changed or what, but the weather information is available on their site, so I believe meecast should be able to get hold of it as well.

**Comment by vasvlad** [comment]
fmi.fi source for weather forecast (http://m.fmi.fi/mobile/interfaces/weatherdata.php) is outdated. :(

I need rewrite the code for this source.  But I don't know if I will have free time for this.

**Comment by vasvlad** [comment]
Fixed in version 1.1.41 https://github.com/Meecast/meecast/releases/tag/v1.1.41.4. Try it.

**Comment by Ingvix** [comment]
Seems to work great. Thank you!

**Comment by Ingvix** [comment]
Though now I noticed that some data like the sunrise and sunsets seems to be missing. A bit oddly it seemed to be there when I first installed the new version and refreshed the station but now after reopening the app, it's no longer there.

**Comment by Ingvix** [comment]
Um, now though, as I checked the times were shown again. I'm guessing, whatever the issue is/was, it's probably something else than the data not being parsed for the necessary information. If it seems to happen more often, I'll make another issue.

**Comment by vasvlad** [comment]
I've fixed sunrise problem. Try the new version of Meecast https://github.com/Meecast/meecast/releases/tag/v1.11.2.1
