### ISSUE TITLE
[Bug] `harbour-meecast-eventview` package not available at OpenRepos

### ISSUE THREAD

**Issue by Olf0** [Meecast/meecast#68]
@vasvlad, when performing [my review WRT the separation of the `event` and `eventview` sub-packages](https://github.com/Meecast/meecast/issues/67), I discovered that the `harbour-meecast-eventview` package is not uploaded on the [Meecast Event View page at OpenRepos](https://openrepos.net/content/vasvlad/meecast-event-view) in addition to the `harbour-meecast-event` package.

The split into two separate packages was explicitly performed to allow appropriate packages for SailfishOS ≥ 4.6.0 and SailfishOS < 4.6.0 to coexist in a single RPM repository, in order to make MeeCast(-Eventview) installable for users of all SailfishOS releases from a single repository (i.e. [yours at OpenRepos](https://openrepos.net/user/678/programs)) again.

Please tell me if I missed an aspect; if I did not, please upload the `harbour-meecast-eventview` package on the [Meecast Event View page at OpenRepos](https://openrepos.net/content/vasvlad/meecast-event-view) (in *addition* to the `harbour-meecast-event` package) now and in the future.

**Comment by Olf0** [comment]
@vasvlad, as already stated: Please name a reason not to upload `harbour-meecast-eventview` package [at OpenRepos](https://openrepos.net/content/vasvlad/meecast-event-view) or just upload it there.

This *may* be the only reason why people report MeeCast from OpenRepos not working properly in contrast to installing them from SailfishOS:Chum.  Then PR #72 would be completely unnecessary!  Unfortunately I have no way to test this, currently.

**Comment by vasvlad** [comment]
No reasons other than my lack of free time. :(
I've just created the new package page

**Comment by Olf0** [comment]
> No reasons other than my lack of free time. :(

This is always fine, though sometimes unfortunate.

> I've just created the new package page: https://openrepos.net/content/vasvlad/meecast-event-view-sailfishos-460 And change name in old package: https://openrepos.net/content/vasvlad/meecast-event-view-sailfishos-460-0 Please check it.

Oh, the idea was to make it easy for users by providing both packages in the same repository: RPM takes care about the "<4.6.0" vs. "≥4.6.0" separation, this is exactly the reason why I named them differently and let them depend on `sailfish-version` mutually exclusive (i.e. either "<4.6.0" or "≥4.6.0").

May I suggest to please revert all these changes (altering the name of the page breaks many postings at FSO linking to it!) and simply also upload `harbour-meecast-eventview` to a OpenRepo page named `https://openrepos.net/content/vasvlad/meecast-event-view`.

**Comment by vasvlad** [comment]
Hmm.  I don't understand your idea. :( I have now implemented your request (reverted everything back). Please check it. I will need to upload both versions of the packages in the future to https://openrepos.net/content/vasvlad/meecast-event-view?

**Comment by Olf0** [comment]
> Hmm. I don't understand your idea. :( 

Sorry, then likely my explanation was not sufficient.  I know discussing by typing messages can be tedious, but IMO we should take the time to achieve mutual understanding (e.g. we are working on the topic "make MeeCast compatible to SailfishOS ≥ 4.6.0" for months, so a couple of days do not make any significant difference).  I really do not feel I am in the position to command you (and you simply execute), even if this is about the specifics of RPM packaging (or CI workflow configuration etc.).

> I have now implemented your request (reverted everything back). Please check it.

Thank you very much!  You may add a single line to this page to notify the few users who manually download RPM packages from OpenRepos to explain the difference of the two packages.
My suggestion for the **description** field at OpenRepos for this page:

The MeeCast eventview widget displays weather information at the top of SailfishOS' eventsview.

Note that the **harbour-meecast-eventview** packages are for SailfishOS ≥ 4.6.0 and the **harbour-meecast-event** for SailfishOS < 4.6.0.

> I will need to upload both versions of the packages in the future to https://openrepos.net/content/vasvlad/meecast-event-view?

Yes.  They all end up in a single RPM repository anyway (hence the different names were also technically necessary), because OpenRepos creates a single RPM repository for each registered user there.
So please also upload the three packages `[harbour-meecast-event-1.11.7-1.{aarch64|armv7hl|i486}.rpm` there.  Then the long story of "making MeeCast compatible to SailfishOS ≥ 4.6.0" is concluded (I hope).

**Comment by vasvlad** [comment]
Done
