### ISSUE TITLE
[Bug] Since version 1.11.8 of MeeCast, no clickable list for the forecast and Pulley-Menu broken

### ISSUE THREAD

**Issue by FingusDE** [Meecast/meecast#79]
Since version 1.11.8 of MeeCast, I cannot click on the days in the list for the forecast. It doesn’t open any further information and seems not to recognize the click. Something broke since the last version update. Additionally, the screen doesn’t scroll down when trying to reach the pulley menu. See the screenshot:

![d92399f8c653e2a8923e78b4c50167e934881729](https://github.com/user-attachments/assets/098f5548-a399-4d3c-a34d-896fa07d0ab5)

On Jolla C2.

**Comment by Olf0** [comment]
@FingusDE, please do provide the information requested when filling out [the corresponding issue template](https://github.com/Meecast/meecast/issues/new?assignees=&labels=bug&projects=&template=bug-template.md&title=%5BBug%5D+) and do use it in the future.

**Comment by FingusDE** [comment]
When removing the Location and add it again (using foreca) its fixed temporary until i close the app and start again, then the same bug appears.

**Comment by Olf0** [comment]
@eson57 [reports](https://forum.sailfishos.org/t/sfos-4-6-foreca-meecast-how-to-re-enable-weather-infos-in-events-view/18678/102?u=olf):
I had the same issue with not more then one location and provider yr.no.
When I added one more location with provider foreca, it suddenly worked on both locations. :thinking:

**Comment by Olf0** [comment]
> @FingusDE, please do provide the information requested when filling out [the corresponding issue template](https://github.com/Meecast/meecast/issues/new?assignees=&labels=bug&projects=&template=bug-template.md&title=%5BBug%5D+) for this issue …

@FingusDE, please do: Open that template in another tab, copy over the markdown code into a new comment here and provide all the missing information.
Thanks!

**Comment by FingusDE** [comment]
Exact **OS NAME** and **OS VERSION**: 
SailfishOS 5.0.0.29

**HARDWARE**:
Jolla C2

**MeeCast VERSION**: 
1.11.8

Installed **MeeCast PACKAGES**: 
Installiert  harbour-meecast-1.11.8-1.4.1.jolla.aarch64 (installed)
Installiert  harbour-meecast-daemon-1.11.8-1.4.1.jolla.aarch64 (installed)
Installiert  harbour-meecast-eventview-1.11.8-1.4.1.jolla.aarch64 (installed)

**SOURCE of MeeCast PACKAGES**: 
Not sure anymore Storeman or Chum.

**Weather data SOURCE(s)**: 
foreca.com

**Weather LOCATION(s)**: 
foreca.com:Germany:Havixvbeck

#### BUG DESCRIPTION
Since version 1.11.8 of MeeCast, I cannot click on the days in the list for the forecast. It doesn’t open any further information and seems not to recognize the click. Something broke since the last version update. 

Additionally, the screen doesn’t scroll down when trying to reach the pulley menu.

#### STEPS TO REPRODUCE
Start MeeCast and click on one weekday in the List.

#### ADDITIONAL INFORMATION
When removing the Location and add it again (using foreca) its fixed temporary until i close the app and start again, then the same bug appears.

**Comment by FingusDE** [comment]
Fixed, thank you very much for the stunning good work!
